### ISSUE TITLE
Using the OkHttp3Util.syncPost method in smart-doc to push to tornado results in an error.

### ISSUE THREAD

**Issue by li7hai26** [TongchengOpenSource/smart-doc#104]
## Your Environment
Using the OkHttp3Util.syncPost method in smart-doc to push to Torna results in an error.

**Comment by netdied** [comment]
Could you please take a screenshot of the specific error message?

**Comment by li7hai26** [comment]
The response from the Torna side:
2021-04-13 16:29:07.168 ERROR 1960 --- [io-7700-exec-10] com.gitee.easyopen.ApiInvoker            : Invoking a service request that does not exist

com.gitee.easyopen.exception.ApiException: Invoking a service request that does not exist
	at com.gitee.easyopen.message.ErrorMeta.getException(ErrorMeta.java:85) ~[easyopen-1.16.17.jar:na]
	at com.gitee.easyopen.message.ErrorMeta.getException(ErrorMeta.java:68) ~[easyopen-1.16.17.jar:na]
	at com.gitee.easyopen.ApiInvoker.getApiDefinition(ApiInvoker.java:240) ~[easyopen-1.16.17.jar:na]
	at com.gitee.easyopen.ApiInvoker.doInvoke(ApiInvoker.java:128) ~[easyopen-1.16.17.jar:na]
	at com.gitee.easyopen.ApiInvoker.invoke(ApiInvoker.java:57) ~[easyopen-1.16.17.jar:na]
	at com.gitee.easyopen.template.InvokeTemplate.processInvoke(InvokeTemplate.java:28) [easyopen-1.16.17.jar:na]
	at com.gitee.easyopen.support.ApiController.index(ApiController.java:207) [easyopen-1.16.17.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_282]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]

**Comment by li7hai26** [comment]
The solution is to change
```java
String responseMsg = OkHttp3Util.syncPost(apiConfig.getOpenUrl(), requestJson);
```
to
```java
String responseMsg = OkHttp3Util.syncPostJson(apiConfig.getOpenUrl(), new Gson().toJson(requestJson));
```

**Comment by li7hai26** [comment]
Can I submit a PR?

**Comment by netdied** [comment]
Sure, but I'm a bit puzzled by this error. Why change it to postJson...

**Comment by li7hai26** [comment]
Torna has a specific logic for handling this request.
Torna uses easyopen, and the ApiParamParser code in easyopen has the following logic:

```java
public String getJson(HttpServletRequest request) throws Exception {
    String requestJson = null;

    if (RequestUtil.isGetRequest(request)) {
        Map<String, Object> params = RequestUtil.convertRequestParamsToMap(request);
        requestJson = JSON.toJSONString(params);
    } else {
        String contectType = request.getContentType();

        if (contectType == null) {
            contectType = "";
        }

        contectType = contectType.toLowerCase();

        // JSON or plain text format
        if (contectType.contains(CONTENT_TYPE_JSON) || contectType.contains(CONTENT_TYPE_TEXT)) {
            requestJson = RequestUtil.getText(request);
        } else if (contectType.contains(CONTENT_TYPE_MULTIPART)) {
            // File upload format
            requestJson = this.parseUploadRequest(request);
        } else {
            Map<String, Object> params = RequestUtil.convertRequestParamsToMap(request);
            requestJson = JSON.toJSONString(params);
        }
    }

    return requestJson;
}
```
