### ISSUE TITLE
Reading Enum dictionary NoSuchMethod

### ISSUE THREAD

**Issue by bestK** [TongchengOpenSource/smart-doc#214]
## Your Environment (The Environment You Experienced the Bug In)
* smart-doc version: The latest version
* plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version (maven or gradle): maven

## Expected Behavior (What You Expect to Happen)

Normal usage

## Current Behavior (What is Actually Happening)

`java.lang.NoSuchMethodException: cn.xx.core.consts.HttpCodeExpand.getValue()
	at java.lang.Class.getMethod(Class.java:1786)
	at com.power.common.util.EnumUtil.getEnumInformation(EnumUtil.java:38)`

## Possible Solution (Suggestions for Fixing the Bug)

N/A

## Steps to Reproduce (Steps to Reproduce the Bug, Please Provide Code Examples if Possible)

```
public enum HttpCodeExpand {

    /**
     * Business operation exception
     */
    BUSINESS("100", "Business operation exception"),

    /**
     * 200 Request success
     */
    OK("200", "Operation successful"),

    /**
     * 207 Frequent operations
     */
    MULTI_STATUS("207", "Sorry, your operations are too frequent!"),
    /**
     * Requested resource does not exist
     */
    NOT_FOUND("404", "Requested resource does not exist."),
    /**
     * 303 Login failed
     */
    LOGIN_FAIL("303", "Login failed"),
    /**
     * 400 Request parameters are incorrect
     */
    BAD_REQUEST("400", "Request parameters are incorrect"),
    /**
     * 401 Not logged in
     */
    UNAUTHORIZED("401", "Sorry, login expired. Please log in again!"),
    /**
     * 403 No permission
     */
    FORBIDDEN("403", "Sorry, you do not have permission to access this resource."),
    /**
     * 408 Request timed out
     */
    REQUEST_TIMEOUT("408", "Sorry, your request has timed out, please try again later."),
    /**
     * 800 Database operation exception
     */
    DATABASE_BASE("800", "Database operation exception"),
    /**
     * 992 Request internal interface exception
     */
    RPC_REQUEST("992", "Request internal interface exception"),
    /**
     * 993 Idempotent operation
     */
    IDEMPOTENCY("993", "Idempotent operation"),
    /**
     * 994 Lock acquisition exception
     */
    LOCK("994", "Lock acquisition exception"),
    /**
     * 995 Data parsing exception
     */
    DATA_PARSE("995", "Data parsing exception"),

    /**
     * File operation abnormality
     */
    FILE_OPERATION_ABNORMAL("996", "File operation abnormal."),

    /**
     * Invalid request
     */
    INVALID_REQUEST("997", "Invalid request"),

    /**
     * Invalid signature
     */
    SIGN_INVALID("998", "Invalid signature"),

    /**
     * Request third-party resource exception
     */
    REQUEST_INTERFACE("999", "Request third-party resource exception."),

    /**
     * 500 Server error
     */
    INTERNAL_SERVER_ERROR("500", "Sorry, an unknown exception occurred inside the server.");


    private final String value;
    private final String desc;

    HttpCodeExpand(String value, String desc) {
        this.value = value;
        this.desc = desc;
    }

    public String value() {
        return this.value;
    }

    public String msg() {
        return this.desc;
    }

    public String getValue() {
        return this.value;
    }

    public String getDesc() {
        return this.desc;
    }
}
```

**Comment by bestK** [comment]
In a multi-module project, configure the plugin under the root POM, and simply add the JSON to the specific parent.
