### ISSUE TITLE
smart-doc-maven-plugin 2.4.1  Error: could not match input

### ISSUE THREAD

**Issue by lanhaifeng** [TongchengOpenSource/smart-doc#225]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):2.4.1
* build tool version(maven or gradle):maven

use smart-doc-maven-plugin execute mvn smart-doc html fail，but smart-doc-maven-plugin 2.3.1 execute success, so what should I do?

Exception in thread "main" java.lang.Error: Error: could not match input
	at com.thoughtworks.qdox.parser.impl.JFlexLexer.zzScanError(JFlexLexer.java:1984)
	at com.thoughtworks.qdox.parser.impl.JFlexLexer.yylex(JFlexLexer.java:3328)
	at com.thoughtworks.qdox.parser.impl.JFlexLexer.lex(JFlexLexer.java:1663)
	at com.thoughtworks.qdox.parser.impl.Parser.yylex(Parser.java:1949)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:2045)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1944)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:136)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:168)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:163)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.lambda$loadSourcesDependency$3(BaseDocsGeneratorMojo.java:271)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo$$Lambda$13/256522893.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.loadSourcesDependency(BaseDocsGeneratorMojo.java:258)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.lambda$loadSourcesDependencies$2(BaseDocsGeneratorMojo.java:233)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo$$Lambda$12/140702728.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.loadSourcesDependencies(BaseDocsGeneratorMojo.java:209)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.buildJavaProjectBuilder(BaseDocsGeneratorMojo.java:191)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.execute(BaseDocsGeneratorMojo.java:144)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:355)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by shalousun** [comment]
https://smart-doc-group.github.io/#/zh-cn/QA?id=could-not-match-input？

**Comment by lanhaifeng** [comment]
thank you, I get it!
