### ISSUE TITLE
Exception in thread "main" java.lang.Error: Error: could not match input

### ISSUE THREAD

**Issue by longma8520** [TongchengOpenSource/smart-doc#367]
Executing "mvn -Dfile.encoding=UTF-8 smart-doc:torna-rest" results in an error.

`Exception in thread "main" java.lang.Error: Error: could not match input
        at com.thoughtworks.qdox.parser.impl.JFlexLexer.zzScanError(JFlexLexer.java:1997)
        at com.thoughtworks.qdox.parser.impl.JFlexLexer.yylex(JFlexLexer.java:3385)
        at com.thoughtworks.qdox.parser.impl.JFlexLexer.lex(JFlexLexer.java:1676)
        at com.thoughtworks.qdox.parser.impl.Parser.yylex(Parser.java:1960)
        at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:2056)
        at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1955)
        at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
        at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
        at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
        at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:136)
        at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:168)
        at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:163)
        at com.smartdoc.mojo.BaseDocsGeneratorMojo.lambda$loadSourcesDependency$4(BaseDocsGeneratorMojo.java:254)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.smartdoc.mojo.BaseDocsGeneratorMojo.loadSourcesDependency(BaseDocsGeneratorMojo.java:241)
        at com.smartdoc.mojo.BaseDocsGeneratorMojo.lambda$loadSourcesDependencies$3(BaseDocsGeneratorMojo.java:216)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.smartdoc.mojo.BaseDocsGeneratorMojo.loadSourcesDependencies(BaseDocsGeneratorMojo.java:192)
        at com.smartdoc.mojo.BaseDocsGeneratorMojo.buildJavaProjectBuilder(BaseDocsGeneratorMojo.java:174)
        at com.smartdoc.mojo.BaseDocsGeneratorMojo.execute(BaseDocsGeneratorMojo.java:128)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.Mojo`

configuration
```
<plugin>
   <groupId>com.github.shalousun</groupId>
   <artifactId>smart-doc-maven-plugin</artifactId>
   <version>2.5.2</version>
   <configuration>
      <configFile>./src/main/resources/smart-doc.json</configFile>
      <projectName>xxxx</projectName>
   </configuration>
   <executions>
      <execution>
         <phase>package</phase>
      </execution>
   </executions>
</plugin>
<plugin>
```

**Comment by shalousun** [comment]
https://smart-doc-group.github.io/#/zh-cn/faq?id=could-not-match-input%ef%bc%9f

**Comment by longma8520** [comment]
> https://smart-doc-group.github.io/#/zh-cn/faq?id=could-not-match-input%ef%bc%9f

Thanks. After excluding the problematic jar, the issue is solved
