### ISSUE TITLE
When the return value object uses Void (java.lang.Void), it will result in an infinite loop.

### ISSUE THREAD

**Issue by shanggn** [TongchengOpenSource/smart-doc#4]
When the interface's return value or parameters, property references are self-referential, it will lead to an infinite loop and ultimately cause a memory overflow.
`java.lang.OutOfMemoryError: Java heap space

	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.power.doc.builder.SourceBuilder.buildJson(SourceBuilder.java:966)
	at com.power.doc.builder.SourceBuilder.buildJson(SourceBuilder.java:966)
	at com.power.doc.builder.SourceBuilder.buildJson(SourceBuilder.java:966)
	at com.power.doc.builder.SourceBuilder.buildJson(SourceBuilder.java:966)`

**Comment by netdied** [comment]
Can you provide a specific example? Or try upgrading to version 1.7.5 or above.
能给出你的具体例子么？或者升级到1.7.5以上版本试一下

**Comment by shanggn** [comment]
Sorry, because there are several methods in the same class, I thought the infinite loop was caused by nested objects. After testing each method, it turns out to be caused by a method with a return type of Void object.

不好意思，因为我同一个类里面好几个方法，我看到死循环以为是嵌套对象导致的，实际挨个方法测试下来，是因为一个返回值为Void对象的方法
```
@GetMapping("test")
public Result<Void> test() {
        return Result.success(null);
}
```

**Comment by shangguannan** [comment]
不好意思，因为我同一个类里面好几个方法，我看到死循环以为是嵌套对象导致的，实际挨个方法测试下来，是因为一个返回值为Void对象的方法

`@GetMapping("test")
    public Result<Void> test() {
        return Result.success(null);
    }`

**Comment by netdied** [comment]
Currently, you can directly ignore the Void.
目前你可以直接
```
 Result test(){
return Result.ok();
}
```

**Comment by netdied** [comment]
已修改 你可以下载最新的代码重新打包一下

**Comment by shalousun** [comment]
This bug has been fixed
