### ISSUE TITLE
An error occurred while upgrading from 2.3.2 to 2.6.1.

### ISSUE THREAD

**Issue by yepingping** [TongchengOpenSource/smart-doc#436]
## Your Environment(您的使用环境)

* springboot 2.6.7
* smart-doc  2.6.1 及以上:
* plugin version (smart-doc-maven-plugin 2.6.1 ):
* build tool version(maven3.6.3):

## Expected Behavior(您期望的结果)
Use the command
 ```bash
mvn smart-doc:html -Dfile.encoding=UTF-8  -pl :fox-printing-api -am
```
It can correctly execute and produce HTML documents.

## Current Behavior(当前结果)
  **It can normally generate HTML-related documents, but there will be abnormal error messages.**
 The following is the error content after executing the command.
```java

Exception in thread "main" java.lang.Error: Error: could not match input
	at com.thoughtworks.qdox.parser.impl.JFlexLexer.zzScanError(JFlexLexer.java:1997)
	at com.thoughtworks.qdox.parser.impl.JFlexLexer.yylex(JFlexLexer.java:3385)
	at com.thoughtworks.qdox.parser.impl.JFlexLexer.lex(JFlexLexer.java:1676)
	at com.thoughtworks.qdox.parser.impl.Parser.yylex(Parser.java:1960)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:2056)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1955)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:136)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:168)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:163)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.lambda$loadSourcesDependency$4(BaseDocsGeneratorMojo.java:256)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo$$Lambda$27/543028700.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.loadSourcesDependency(BaseDocsGeneratorMojo.java:243)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.lambda$loadSourcesDependencies$3(BaseDocsGeneratorMojo.java:217)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo$$Lambda$26/1917860633.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.loadSourcesDependencies(BaseDocsGeneratorMojo.java:196)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.buildJavaProjectBuilder(BaseDocsGeneratorMojo.java:178)
	at com.smartdoc.mojo.BaseDocsGeneratorMojo.execute(BaseDocsGeneratorMojo.java:136)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

Process finished with exit code 1
```

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
``` xml
<plugin>
                    <groupId>com.github.shalousun</groupId>
                    <artifactId>smart-doc-maven-plugin</artifactId>
                    <version>${smart-doc.version}</version>
                    <configuration>
                      
                        <configFile>${basedir}/src/main/resources/smart-doc.json</configFile>
                
                        <projectName>v1</projectName>
                      
                        <excludes>
                            <exclude>cn.hutool:hutool-all</exclude>
                            <exclude>org.springframework.boot:spring-boot-devtools</exclude>
                        </excludes>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>html</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```

## Context(Bug影响描述)
It is unclear whether the above error content will result in any missing or abnormally displayed content in the generated document.
以上错误内容不知道是否会对文档的生成内容是否有缺失或异常显示内容。

**Comment by shalousun** [comment]
@yepingping https://smart-doc-group.github.io/#/zh-cn/faq

**Comment by yepingping** [comment]
@shalousun  Thank you, the issue has been resolved following the steps in the FAQ.

```bash
mvn -X -Dfile.encoding=UTF-8 smart-doc:html
```
Search for "smart-doc loaded jar source:" in the console log, and the JAR that is problematic will be the one loaded after the last "smart-doc loaded jar source:" log. Then, go to the plugin configuration and exclude this JAR package.
从控制台日志中搜索smart-doc loaded jar source:, 最后一个smart-doc loaded jar source:日志后面加载的jar就有问题的jar。然后自己去查看插件的配置把这个jar包排除掉即可。
